import { ArrowLeft, Download, Eye, Printer, ReceiptText, Save, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { DataTable } from "../../components/DataTable";
import { useToast } from "../../components/Toast";
import { ErrorState, Field, LoadingState, Modal, PageHeader } from "../../components/ui";
import { api, apiMessage } from "../../lib/api";
import { money, shortDate } from "../../lib/format";
import { useAuthStore } from "../../stores/auth";
import type { ApiResponse, DataRecord, Paginated } from "../../types/api";

const normalize = (data: DataRecord[] | Paginated<DataRecord>): Paginated<DataRecord> => Array.isArray(data) ? { items: data, total: data.length, page: 1, page_size: data.length, total_pages: 1 } : data;

export function PaymentsPage() {
  const [data, setData] = useState<Paginated<DataRecord>>({ items: [], total: 0, page: 1, page_size: 20, total_pages: 1 }); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [cancel, setCancel] = useState<DataRecord | null>(null); const [reason, setReason] = useState(""); const { showToast } = useToast(); const can = useAuthStore((s) => s.can);
  async function load(page = data.page) { setLoading(true); try { const r = await api.get<ApiResponse<DataRecord[] | Paginated<DataRecord>>>("/payments", { params: { page, page_size: 20, limit: 20, skip: (page - 1) * 20 } }); setData(normalize(r.data.data)); } catch (e) { setError(apiMessage(e)); } finally { setLoading(false); } }
  useEffect(() => { load(1); }, []);
  const filtered = useMemo(() => data.items.filter((r) => JSON.stringify(r).toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))), [data.items, search]);
  async function cancelPayment() { if (!cancel) return; try { await api.post(`/payments/${cancel.id}/cancel`, { cancel_reason: reason }); showToast("Ödeme iptal edildi", "Borç bakiyesi yeniden hesaplandı."); setCancel(null); await load(); } catch (e) { showToast("İptal edilemedi", apiMessage(e), "error"); } }
  return <><PageHeader eyebrow="Finans" title="Tahsilatlar" description="Tüm şubelerde alınan ödemeleri ve iptal durumlarını izleyin.">{can("finance.write") && <Link className="btn btn-primary" to="/finance/payments/new"><ReceiptText size={16} />Tahsilat al</Link>}</PageHeader>{loading ? <div className="card"><LoadingState /></div> : error ? <div className="card"><ErrorState message={error} retry={() => load()} /></div> : <DataTable rows={filtered} columns={[{ key: "student_name", label: "Öğrenci", subKey: "student_id" }, { key: "amount", label: "Tutar", type: "money" }, { key: "payment_method", label: "Yöntem" }, { key: "payment_date", label: "Tarih", type: "date" }, { key: "status", label: "Durum", type: "status" }]} search={search} onSearch={setSearch} page={data.page} totalPages={data.total_pages} total={data.total} onPage={load} detailBase="/finance/payments" canEdit={false} filters={can("finance.write") && filtered.length ? <button className="btn btn-danger" onClick={() => setCancel(filtered[0])}><XCircle size={15} />Ödeme iptal et</button> : undefined} />}<Modal open={Boolean(cancel)} title="Ödemeyi iptal et" description="İşlem silinmez, ters kayıt olarak finans geçmişinde korunur." onClose={() => setCancel(null)} actions={<><button className="btn btn-secondary" onClick={() => setCancel(null)}>Vazgeç</button><button className="btn btn-danger" onClick={cancelPayment}><XCircle size={15} />İptal et</button></>}><Field label="İptal nedeni"><textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="İptal gerekçesini yazın" /></Field></Modal></>;
}

interface PaymentForm { debt_id: string; amount: string; payment_method: string; notes: string }
export function PaymentFormPage() {
  const [debts, setDebts] = useState<DataRecord[]>([]); const [loading, setLoading] = useState(true); const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<PaymentForm>(); const { showToast } = useToast(); const navigate = useNavigate();
  useEffect(() => { api.get<ApiResponse<DataRecord[] | Paginated<DataRecord>>>("/debts", { params: { page_size: 100, limit: 100 } }).then((r) => setDebts(normalize(r.data.data).items.filter((d) => !["PAID", "CANCELLED"].includes(String(d.status))))).catch((e) => showToast("Borçlar yüklenemedi", apiMessage(e), "error")).finally(() => setLoading(false)); }, []);
  const selected = debts.find((debt) => debt.id === watch("debt_id"));
  async function submit(values: PaymentForm) { try { const response = await api.post<ApiResponse<{ receipt_id: string }>>("/payments", values); showToast("Tahsilat tamamlandı", "Makbuz otomatik olarak oluşturuldu."); navigate(response.data.data?.receipt_id ? `/finance/receipts/${response.data.data.receipt_id}` : "/finance/payments"); } catch (e) { showToast("Tahsilat alınamadı", apiMessage(e), "error"); } }
  if (loading) return <div className="card"><LoadingState /></div>;
  return <><PageHeader eyebrow="Finans" title="Yeni tahsilat" description="Öğrenci borcunu seçin; kalan tutarı aşmadan güvenli ödeme alın."><Link className="btn btn-secondary" to="/finance/payments"><ArrowLeft size={16} />Listeye dön</Link></PageHeader><form className="card form-card" onSubmit={handleSubmit(submit)}><div className="form-section"><h2>Ödeme bilgileri</h2><p>Makbuz, işlem tamamlandığında otomatik üretilir.</p><div className="form-grid"><Field label="Borç kaydı" required error={errors.debt_id?.message}><select {...register("debt_id", { required: "Borç seçimi zorunludur." })}><option value="">Borç seçin</option>{debts.map((debt) => <option key={debt.id} value={debt.id}>{String(debt.student_name || debt.student_id)} · {money(debt.remaining_amount ?? debt.amount)}</option>)}</select></Field><Field label="Ödeme tutarı" required error={errors.amount?.message}><input type="number" step="0.01" max={selected ? Number(selected.remaining_amount ?? selected.amount) : undefined} {...register("amount", { required: "Tutar zorunludur.", min: { value: .01, message: "Tutar 0'dan büyük olmalı." } })} /></Field><Field label="Ödeme yöntemi" required error={errors.payment_method?.message}><select {...register("payment_method", { required: "Yöntem seçin." })}><option value="">Seçiniz</option><option value="CASH">Nakit</option><option value="CREDIT_CARD">Kredi kartı</option><option value="BANK_TRANSFER">Banka havalesi</option><option value="EFT">EFT</option><option value="OTHER">Diğer</option></select></Field><Field label="Açıklama" full><textarea {...register("notes")} /></Field></div></div><div className="form-actions"><Link className="btn btn-secondary" to="/finance/payments">Vazgeç</Link><button className="btn btn-primary" disabled={isSubmitting}><Save size={16} />Tahsilatı tamamla</button></div></form></>;
}

export function ReceiptsPage() {
  const [rows, setRows] = useState<DataRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  useEffect(() => { api.get<ApiResponse<DataRecord[] | Paginated<DataRecord>>>("/receipts", { params: { page_size: 100 } }).then((r) => setRows(normalize(r.data.data).items)).catch((e) => setError(apiMessage(e))).finally(() => setLoading(false)); }, []);
  const filtered = rows.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader eyebrow="Finans" title="Makbuzlar" description="Tahsilatların resmi belgelerini görüntüleyin, indirin veya yazdırın." />{loading ? <div className="card"><LoadingState /></div> : error ? <div className="card"><ErrorState message={error} /></div> : <DataTable rows={filtered} columns={[{ key: "receipt_number", label: "Makbuz no" }, { key: "issued_at", label: "Düzenlenme", type: "date" }, { key: "remaining_debt", label: "Kalan borç", type: "money" }, { key: "status", label: "Durum", type: "status" }]} search={search} onSearch={setSearch} page={1} totalPages={1} total={filtered.length} onPage={() => {}} detailBase="/finance/receipts" />}</>;
}

export function ReceiptDetailPage() {
  const { id } = useParams(); const [record, setRecord] = useState<DataRecord | null>(null); const [error, setError] = useState(""); const { showToast } = useToast();
  useEffect(() => { api.get<ApiResponse<DataRecord>>(`/receipts/${id}`).then((r) => setRecord(r.data.data)).catch((e) => setError(apiMessage(e))); }, [id]);
  async function download(path: string) { try { const response = await api.get(path, { responseType: "blob" }); const url = URL.createObjectURL(response.data); try { const a = document.createElement("a"); a.href = url; a.download = `${record?.receipt_number || "makbuz"}.pdf`; a.click(); } finally { URL.revokeObjectURL(url); } } catch (e) { showToast("Makbuz indirilemedi", apiMessage(e), "error"); } }
  if (error) return <div className="card"><ErrorState message={error} /></div>; if (!record) return <div className="card"><LoadingState /></div>;
  return <><PageHeader eyebrow="Makbuz" title={String(record.receipt_number)} description="Tahsilata ait doğrulanmış belge bilgileri."><Link className="btn btn-secondary" to="/finance/receipts"><ArrowLeft size={16} />Listeye dön</Link><button className="btn btn-secondary" onClick={() => download(`/receipts/${id}/pdf`)}><Download size={16} />PDF indir</button><Link className="btn btn-primary" to={`/finance/receipts/${id}/print`}><Printer size={16} />Yazdır</Link></PageHeader><div className="card form-card"><div style={{ display: "flex", alignItems: "center", gap: 13, paddingBottom: 20, borderBottom: "1px solid var(--line)" }}><div className="brand-mark"><ReceiptText size={22} /></div><div><strong style={{ font: "800 18px Manrope" }}>Okul360 Tahsilat Makbuzu</strong><div className="cell-sub">Belge no: {String(record.receipt_number)}</div></div></div><div className="detail-list" style={{ marginTop: 24 }}><div className="detail-item"><small>Düzenlenme tarihi</small><strong>{shortDate(record.issued_at)}</strong></div><div className="detail-item"><small>Durum</small><strong>{String(record.status)}</strong></div><div className="detail-item"><small>Ödeme kaydı</small><strong>{String(record.payment_id)}</strong></div><div className="detail-item"><small>Kalan borç</small><strong>{money(record.remaining_debt)}</strong></div></div></div></>;
}

export function PaymentDetailPage() {
  const { id } = useParams(); const [record, setRecord] = useState<DataRecord | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.get<ApiResponse<DataRecord>>(`/payments/${id}`).then((r) => setRecord(r.data.data)).catch((e) => setError(apiMessage(e))); }, [id]);
  if (error) return <ErrorState message={error} />; if (!record) return <LoadingState />;
  return <><PageHeader eyebrow="Tahsilat" title={money(record.amount)} description={`${shortDate(record.payment_date)} tarihli ödeme kaydı.`}><Link className="btn btn-secondary" to="/finance/payments"><ArrowLeft size={16} />Listeye dön</Link>{record.receipt_id && <Link className="btn btn-primary" to={`/finance/receipts/${record.receipt_id}`}><Eye size={16} />Makbuzu aç</Link>}</PageHeader><div className="card form-card detail-list">{Object.entries(record).filter(([key]) => !key.includes("id")).map(([key, value]) => <div className="detail-item" key={key}><small>{key.replaceAll("_", " ")}</small><strong>{String(value ?? "—")}</strong></div>)}</div></>;
}
