import { ArrowLeft, Download, File, Trash2, Upload } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useToast } from "../../components/Toast";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "../../components/ui";
import { api, apiMessage } from "../../lib/api";
import { shortDate, titleCase } from "../../lib/format";
import { useAuthStore } from "../../stores/auth";
import type { ApiResponse, DataRecord } from "../../types/api";

export function StudentFilesPage() {
  const { id } = useParams(); const [files, setFiles] = useState<DataRecord[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [category, setCategory] = useState("OTHER"); const input = useRef<HTMLInputElement>(null); const { showToast } = useToast(); const [error, setError] = useState(""); const canWrite = useAuthStore((state) => state.can("student.write"));
  async function load() { setLoading(true); setError(""); try { const r = await api.get<ApiResponse<DataRecord[]>>(`/students/${id}/files`); setFiles(r.data.data || []); } catch (e) { setError(apiMessage(e)); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [id]);
  async function upload() { const file = input.current?.files?.[0]; if (!file || !canWrite) return; if (file.size > 10 * 1024 * 1024) { showToast("Dosya yüklenemedi", "Dosya boyutu 10 MB sınırını aşıyor.", "error"); return; } const form = new FormData(); form.append("file", file); form.append("category", category); setUploading(true); try { await api.post(`/students/${id}/files`, form); showToast("Dosya yüklendi", file.name); if (input.current) input.current.value = ""; await load(); } catch (e) { showToast("Dosya yüklenemedi", apiMessage(e), "error"); } finally { setUploading(false); } }
  async function remove(fileId: string) { try { await api.delete(`/students/${id}/files/${fileId}`); showToast("Dosya kaldırıldı"); await load(); } catch (e) { showToast("Dosya kaldırılamadı", apiMessage(e), "error"); } }
  async function download(file: DataRecord) { try { const r = await api.get(`/students/${id}/files/${file.id}/download`, { responseType: "blob" }); const url = URL.createObjectURL(r.data); try { const a = document.createElement("a"); a.href = url; a.download = String(file.original_name || file.file_name || "dosya"); a.click(); } finally { URL.revokeObjectURL(url); } } catch (e) { showToast("Dosya indirilemedi", apiMessage(e), "error"); } }
  return <><PageHeader eyebrow="Öğrenci dosyası" title="Belgeler" description="Kimlik, sağlık raporu ve sözleşmeleri güvenli öğrenci kaydında tutun."><Link className="btn btn-secondary" to={`/students/${id}`}><ArrowLeft size={16} />Öğrenciye dön</Link></PageHeader><div className="card">{canWrite && <div className="toolbar"><select className="filter-select" value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Dosya kategorisi"><option value="IDENTITY">Kimlik</option><option value="HEALTH_REPORT">Sağlık raporu</option><option value="REGISTRATION_CONTRACT">Kayıt sözleşmesi</option><option value="PAYMENT_CONTRACT">Ödeme sözleşmesi</option><option value="PHOTO">Fotoğraf</option><option value="OTHER">Diğer</option></select><input ref={input} type="file" className="filter-select" accept=".pdf,.jpg,.jpeg,.png,.docx" aria-label="Yüklenecek dosya" /><button className="btn btn-primary" onClick={upload} disabled={uploading}><Upload size={16} />{uploading ? "Yükleniyor…" : "Yükle"}</button></div>}{loading ? <LoadingState /> : error ? <ErrorState message={error} retry={load} /> : files.length === 0 ? <EmptyState title="Henüz belge yüklenmemiş" description="Dosya türünü seçip ilk öğrenci belgesini yükleyin." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Dosya</th><th>Kategori</th><th>Yüklenme</th><th style={{ textAlign: "right" }}>İşlem</th></tr></thead><tbody>{files.map((item) => <tr key={item.id}><td><div className="inline" style={{ gap: 10 }}><div className="quick-icon"><File size={16} /></div><div><div className="cell-main">{String(item.original_name || item.file_name)}</div><div className="cell-sub">{String(item.mime_type || "Belge")}</div></div></div></td><td>{titleCase(item.category)}</td><td>{shortDate(item.created_at)}</td><td><div className="table-actions"><button className="btn btn-ghost btn-icon" onClick={() => download(item)} aria-label={`${String(item.original_name || item.file_name)} dosyasını indir`}><Download size={15} /></button>{canWrite && <button className="btn btn-ghost btn-icon" onClick={() => remove(item.id)} aria-label={`${String(item.original_name || item.file_name)} dosyasını kaldır`}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div>}</div></>;
}
