import { ChevronLeft, ChevronRight, Eye, Pencil, Search, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { money, shortDate, titleCase } from "../lib/format";
import type { ColumnConfig, DataRecord } from "../types/api";
import { Badge, EmptyState } from "./ui";

function cellValue(row: DataRecord, column: ColumnConfig) {
  const value = row[column.key];
  if (column.type === "status") return <Badge value={typeof value === "boolean" ? (value ? "ACTIVE" : "PASSIVE") : value} />;
  if (column.type === "date") return shortDate(value);
  if (column.type === "money") return <strong>{money(value)}</strong>;
  if (column.type === "roles") return Array.isArray(value) ? (value as Array<{ name?: string }>).map((role) => role.name).filter(Boolean).join(", ") || "—" : "—";
  if (column.type === "person") return <div><div className="cell-main">{String(value || "")} {String(row[column.subKey || "last_name"] || "")}</div><div className="cell-sub">{String(row.email || row.student_number || "")}</div></div>;
  if (column.type === "capacity") return <div style={{ minWidth: 100 }}><strong>{String(row.occupancy ?? 0)} / {String(value || 0)}</strong><div className="progress" style={{ marginTop: 6 }}><span style={{ width: `${Math.min(100, Number(row.occupancy || 0) / Math.max(1, Number(value || 1)) * 100)}%` }} /></div></div>;
  return <div><span className={column.key === "name" || column.key === "first_name" ? "cell-main" : ""}>{["debt_type", "relationship"].includes(column.key) ? titleCase(value) : String(value ?? "—")}</span>{column.subKey && row[column.subKey] && <div className="cell-sub">{String(row[column.subKey])}</div>}</div>;
}

export function DataTable({ rows, columns, search, onSearch, page, totalPages, total, onPage, editBase, detailBase, canEdit, onDelete, filters }: { rows: DataRecord[]; columns: ColumnConfig[]; search: string; onSearch: (value: string) => void; page: number; totalPages: number; total: number; onPage: (page: number) => void; editBase?: string; detailBase?: string; canEdit?: boolean; onDelete?: (row: DataRecord) => void; filters?: React.ReactNode }) {
  return <div className="card"><div className="toolbar"><div className="search"><Search size={16} /><input value={search} onChange={(e) => onSearch(e.target.value)} placeholder="Listede ara…" aria-label="Listede ara" /></div>{filters}</div>{rows.length === 0 ? <EmptyState title="Aramanızla eşleşen kayıt yok" description="Filtreleri temizleyin veya yeni bir kayıt ekleyin." /> : <><div className="table-wrap"><table className="data-table"><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}<th style={{ textAlign: "right" }}>İşlemler</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key}>{cellValue(row, column)}</td>)}<td><div className="table-actions">{detailBase && <Link className="btn btn-ghost btn-icon" title="Detayı aç" aria-label="Detayı aç" to={`${detailBase}/${row.id}`}><Eye size={15} /></Link>}{canEdit && editBase && <Link className="btn btn-ghost btn-icon" title="Düzenle" aria-label="Düzenle" to={`${editBase}/${row.id}/edit`}><Pencil size={15} /></Link>}{canEdit && onDelete && <button className="btn btn-ghost btn-icon" title="Kaldır" aria-label="Kaldır" onClick={() => onDelete(row)}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div><div className="pagination"><span>Toplam <strong>{total}</strong> kayıt · Sayfa {page}/{Math.max(1, totalPages)}</span><div className="page-buttons"><button disabled={page <= 1} onClick={() => onPage(page - 1)} aria-label="Önceki sayfa"><ChevronLeft size={15} /></button>{Array.from({ length: Math.min(5, Math.max(1, totalPages)) }, (_, i) => Math.max(1, Math.min(page - 2, Math.max(1, totalPages - 4))) + i).filter((n) => n <= Math.max(1, totalPages)).map((n) => <button key={n} className={n === page ? "active" : ""} aria-label={`${n}. sayfa`} aria-current={n === page ? "page" : undefined} onClick={() => onPage(n)}>{n}</button>)}<button disabled={page >= totalPages} onClick={() => onPage(page + 1)} aria-label="Sonraki sayfa"><ChevronRight size={15} /></button></div></div></>}</div>;
}
