import { ArrowLeft, CalendarCheck2, CreditCard, FileText, Pencil, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ErrorState, LoadingState, PageHeader } from "../../components/ui";
import { resources } from "../../config/resources";
import { api, apiMessage } from "../../lib/api";
import { shortDate, titleCase } from "../../lib/format";
import { useAuthStore } from "../../stores/auth";
import type { ApiResponse, DataRecord } from "../../types/api";

export function DetailPage({ resourceKey }: { resourceKey: string }) {
  const config = resources[resourceKey]; const { id } = useParams(); const [record, setRecord] = useState<DataRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const can = useAuthStore((state) => state.can);
  useEffect(() => { api.get<ApiResponse<DataRecord>>(`${config.endpoint}/${id}`).then((r) => setRecord(r.data.data)).catch((e) => setError(apiMessage(e))).finally(() => setLoading(false)); }, [config.endpoint, id]);
  if (loading) return <div className="card"><LoadingState /></div>; if (error || !record) return <div className="card"><ErrorState message={error || "Kayıt bulunamadı."} /></div>;
  const displayName = [record.first_name, record.last_name].filter(Boolean).join(" ") || String(record.name || config.singular);
  return <><PageHeader eyebrow={`${config.singular} profili`} title={displayName} description="Kayıtla ilişkili temel bilgiler ve işlem geçmişi."><Link className="btn btn-secondary" to={`/${resourceKey}`}><ArrowLeft size={16} />Listeye dön</Link>{can(config.permissionWrite) && <Link className="btn btn-primary" to={`/${resourceKey}/${id}/edit`}><Pencil size={16} />Düzenle</Link>}</PageHeader><div className="detail-grid"><div className="card"><div className="card-head"><div><h2>Genel bilgiler</h2><p>Backend kaydından güncel bilgiler</p></div></div><div className="tabs"><button className="tab active">Profil</button>{resourceKey === "students" && <><button className="tab">Veliler</button><button className="tab">Finans</button><button className="tab">Yoklama</button><button className="tab">Dosyalar</button></>}</div><div className="card-pad detail-list">{config.columns.filter((column) => column.key !== "status").map((column) => <div className="detail-item" key={column.key}><small>{column.label}</small><strong>{column.type === "date" ? shortDate(record[column.key]) : titleCase(record[column.key])}</strong></div>)}</div></div><aside className="card card-pad"><h2 style={{ margin: "0 0 15px", font: "700 15px Manrope" }}>Hızlı bağlantılar</h2>{resourceKey === "students" ? <div className="quick-list" style={{ padding: 0 }}><Link className="quick-item" to={`/students/${id}/files`}><div className="quick-icon"><FileText size={16} /></div><div className="quick-copy"><strong>Öğrenci dosyaları</strong><span>Belgeler ve sözleşmeler</span></div></Link><Link className="quick-item" to={`/finance/payments?student_id=${id}`}><div className="quick-icon"><CreditCard size={16} /></div><div className="quick-copy"><strong>Ödeme geçmişi</strong><span>Tahsilat ve makbuzlar</span></div></Link><Link className="quick-item" to={`/attendance?student_id=${id}`}><div className="quick-icon"><CalendarCheck2 size={16} /></div><div className="quick-copy"><strong>Devamsızlık</strong><span>Günlük yoklama geçmişi</span></div></Link></div> : <div className="state" style={{ minHeight: 180, padding: 15 }}><div><UserRound size={28} color="#7fa89d" /><h3>Kayıt aktif</h3><p>İlişkili işlemler ilgili modüllerde görüntülenir.</p></div></div>}</aside></div></>;
}
